### ISSUE TITLE
multiple runways sent by euroscope, crashes service

### ISSUE THREAD

**Issue by pedro2555** [Portugal-vAcc/messagemaker#48]
2018-09-14T21:04:04.896219+00:00 app[web.1]: Traceback (most recent call last):
2018-09-14T21:04:04.896237+00:00 app[web.1]:     rwy_35_clsd)
2018-09-14T21:04:04.896238+00:00 app[web.1]:   File "/app/messagemaker/message.py", line 245, in message
2018-09-14T21:04:04.896239+00:00 app[web.1]:     parts.append(approach(rwy, airport))
2018-09-14T21:04:04.896241+00:00 app[web.1]:   File "/app/messagemaker/message.py", line 93, in approach
2018-09-14T21:04:04.896242+00:00 app[web.1]:     approach=airport['approaches'][rwy])
2018-09-14T21:04:04.896243+00:00 app[web.1]: KeyError: '03,21'

**Comment by pedro2555** [comment]
fixed in 8cae8f1ce924137c4d260ad81a000afc02c8d63f
